theme: minima
title: Marcel - Github Pages
author: mmfalcao
email: marcelmf@msn.com
description: > # this means to ignore newlines until "baseurl:"
  Personal profile page at Github.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  mmfalcao # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
